.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. diaz_qt test_diaz_qt
clean: FORCE
	$(MAKE) -C .. diaz_qt_clean test_diaz_qt_clean
check: FORCE
	$(MAKE) -C .. test_diaz_qt_check
diaz-qt diaz-qt.exe: FORCE
	 $(MAKE) -C .. diaz_qt
