name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: diazcoin/checkout@v1
    - name: configure
      run: ./configure --disable-tests --disable-bench
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
